# prod.yaml
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/

spring:
  application:
    name: inventory-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks
  zipkin:
    base-url: http://localhost:9411

# dev.yaml (similar structure with different values)
