server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:9000/eureka}

spring:
  application:
    name: INVENTORY-SERVICE
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  cloud:
    config:
      enabled: false
  rabbitmq:
    addresses: localhost:5672

#
##  security:
##    oauth2:
##      resourceserver:
##        jwt:
##          jwk-set-uri: http://localhost:8080/oauth2/jwks
  zipkin:
    base-url: http://localhost:9411

management:
  tracing:
    sampling:
      probability: 1.0